import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'zh';

type TranslationKey = keyof typeof translations.en;

const translations = {
  en: {
    dashboard: 'Dashboard',
    companies: 'Companies',
    settings: 'Settings',
    companyCompliance: 'Company Annual Filling',
    companyComplianceManagement: 'Company Annual Filling Management',
    admin: 'Admin',
    logOut: 'Log Out',
    email: 'Email',
    password: 'Password',
    enterPassword: 'Enter your password',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    defaultLogin: 'Default: admin@company.com / admin123',
    loginFailed: 'Login failed',
    dashboardSubtitle: 'Overview of your company annual filling status',
    totalCompanies: 'Total Companies',
    overdue: 'Overdue',
    dueIn30Days: 'Due in 30 Days',
    upcomingDeadlines: 'Upcoming Deadlines',
    viewAll: 'View All',
    noUpcomingDeadlines: 'No upcoming deadlines in the next 30 days',
    manageCompanies: 'Manage your BC companies and compliance deadlines',
    addCompany: 'Add Company',
    searchCompanies: 'Search companies...',
    noCompanies: 'No companies yet. Add your first company to get started.',
    noMatchingCompanies: 'No matching companies found.',
    company: 'Company',
    regNumber: 'Reg. Number',
    regDate: 'Reg. Date',
    gst: 'GST',
    yes: 'Yes',
    no: 'No',
    nextAnnualReturn: 'Next Annual Return',
    nextFiling: 'Next Filing',
    nextGst: 'Next GST',
    annualReturn: 'Annual Return',
    annualFiling: 'Annual Filing',
    gstReturn: 'GST Return',
    days: 'days',
    daysShort: 'd',
    dueVerySoon: 'Due very soon',
    dueWithin30Days: 'Due within 30 days',
    onTrack: 'On track',
    daysOverdue: 'days overdue',
    file: 'File',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    backToCompanies: 'Back to Companies',
    companyNotFound: 'Company not found',
    gstRegistered: 'GST Registered',
    gstNotRegistered: 'GST Not Registered',
    companyDetails: 'Company Details',
    registrationDate: 'Registration Date',
    gstNumber: 'GST Number',
    gstPeriod: 'GST Period',
    lastAnnualReturn: 'Last Annual Return',
    lastAnnualFiling: 'Last Annual Filing',
    lastGstReturn: 'Last GST Return',
    notes: 'Notes',
    deleteCompany: 'Delete Company?',
    deleteConfirm: 'Are you sure you want to delete',
    deleteCannotUndo: 'This action cannot be undone.',
    deleting: 'Deleting...',
    newCompany: 'New Company',
    editCompany: 'Edit Company',
    companyName: 'Company Name',
    address: 'Address',
    registeredForGst: 'Registered for GST',
    selectPeriod: 'Select period',
    monthly: 'Monthly',
    annual: 'Annual',
    lastFiling: 'Last Annual Filing',
    saveCompany: 'Save Company',
    failedToLoadCompany: 'Failed to load company',
    failedToSave: 'Failed to save',
    settingsSubtitle: 'Manage your account and email notifications',
    language: 'Language',
    english: 'English',
    chinese: 'Chinese',
    emailNotificationSettings: 'Email Notification Settings',
    smtpHost: 'SMTP Host',
    smtpPort: 'SMTP Port',
    smtpUsername: 'SMTP Username',
    smtpPassword: 'SMTP Password',
    smtpPasswordPlaceholder: 'Leave empty to keep current',
    fromEmail: 'From Email',
    notificationEmail: 'Notification Email',
    notificationEmailPlaceholder: 'Where to receive alerts',
    sendTestEmail: 'Send Test Email',
    sending: 'Sending...',
    smtpSaved: 'SMTP settings saved successfully',
    testEmailSent: 'Test email sent successfully',
    failedToSendTestEmail: 'Failed to send test email',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordMinLength: 'New password must be at least 6 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordChanged: 'Password changed successfully',
    failedToChangePassword: 'Failed to change password',
    changing: 'Changing...',
  },
  zh: {
    dashboard: '仪表盘',
    companies: '公司',
    settings: '设置',
    companyCompliance: '公司年检',
    companyComplianceManagement: '公司年检管理',
    admin: '管理员',
    logOut: '退出登录',
    email: '邮箱',
    password: '密码',
    enterPassword: '请输入密码',
    signingIn: '登录中...',
    signIn: '登录',
    defaultLogin: '默认：admin@company.com / admin123',
    loginFailed: '登录失败',
    dashboardSubtitle: '公司年检状态概览',
    totalCompanies: '公司总数',
    overdue: '已逾期',
    dueIn30Days: '30天内到期',
    upcomingDeadlines: '即将到期',
    viewAll: '查看全部',
    noUpcomingDeadlines: '未来30天内没有即将到期事项',
    manageCompanies: '管理 BC 公司和合规截止日期',
    addCompany: '新增公司',
    searchCompanies: '搜索公司...',
    noCompanies: '还没有公司。请先新增一个公司。',
    noMatchingCompanies: '没有找到匹配的公司。',
    company: '公司',
    regNumber: '注册号',
    regDate: '注册日期',
    gst: 'GST',
    yes: '是',
    no: '否',
    nextAnnualReturn: '下次年检',
    nextFiling: '下次报税',
    nextGst: '下次 GST',
    annualReturn: '年检',
    annualFiling: '年度报税',
    gstReturn: 'GST 申报',
    days: '天',
    daysShort: '天',
    dueVerySoon: '即将到期',
    dueWithin30Days: '30天内到期',
    onTrack: '正常',
    daysOverdue: '天逾期',
    file: '申报',
    save: '保存',
    saving: '保存中...',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    backToCompanies: '返回公司列表',
    companyNotFound: '未找到公司',
    gstRegistered: '已注册 GST',
    gstNotRegistered: '未注册 GST',
    companyDetails: '公司详情',
    registrationDate: '注册日期',
    gstNumber: 'GST 号码',
    gstPeriod: 'GST 周期',
    lastAnnualReturn: '最近年检',
    lastAnnualFiling: '最近年度报税',
    lastGstReturn: '最近 GST 申报',
    notes: '备注',
    deleteCompany: '删除公司？',
    deleteConfirm: '确定要删除',
    deleteCannotUndo: '此操作无法撤销。',
    deleting: '删除中...',
    newCompany: '新增公司',
    editCompany: '编辑公司',
    companyName: '公司名称',
    address: '地址',
    registeredForGst: '已注册 GST',
    selectPeriod: '选择周期',
    monthly: '每月',
    annual: '每年',
    lastFiling: '最近年度报税',
    saveCompany: '保存公司',
    failedToLoadCompany: '加载公司失败',
    failedToSave: '保存失败',
    settingsSubtitle: '管理账号和邮件提醒',
    language: '语言',
    english: '英文',
    chinese: '中文',
    emailNotificationSettings: '邮件提醒设置',
    smtpHost: 'SMTP 主机',
    smtpPort: 'SMTP 端口',
    smtpUsername: 'SMTP 用户名',
    smtpPassword: 'SMTP 密码',
    smtpPasswordPlaceholder: '留空则保留当前密码',
    fromEmail: '发件邮箱',
    notificationEmail: '提醒收件邮箱',
    notificationEmailPlaceholder: '接收提醒的邮箱',
    sendTestEmail: '发送测试邮件',
    sending: '发送中...',
    smtpSaved: 'SMTP 设置已保存',
    testEmailSent: '测试邮件已发送',
    failedToSendTestEmail: '测试邮件发送失败',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
    passwordMinLength: '新密码至少需要 6 个字符',
    passwordsDoNotMatch: '两次输入的密码不一致',
    passwordChanged: '密码修改成功',
    failedToChangePassword: '修改密码失败',
    changing: '修改中...',
  },
} as const;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return saved === 'zh' || saved === 'en' ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage: setLanguageState,
    t: (key: TranslationKey) => translations[language][key],
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
